import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}) {
  return (
    <div className="bg-gradient-to-r from-green-100/50 via-[#f1f8f5] to-green-100/50  min-h-screen w-full dark:bg-none dark:bg-[#2B2A2A]">
      {children}
    </div>
  );
}
